name: gifthamperz
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  animate_do: ^3.1.2
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  pull_to_refresh: ^2.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  cached_network_image: ^3.2.3
  google_nav_bar: ^5.0.6
  readmore: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_sliders: ^22.2.12
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  animated_theme_switcher: ^2.0.8
  encrypted_shared_preferences: ^3.0.1
  intl: ^0.18.0
  dropdown_button2: ^1.7.2
  marquee: ^2.2.3
  pinput: ^3.0.1
  dio: ^5.0.0
  easy_stepper: ^0.8.3
  dotted_border: ^2.1.0
  razorpay_flutter: ^1.3.6
  ffi: ^2.1.0
  responsive_builder: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pngs/
    - assets/svgs/
    - assets/gif/

  fonts:
    - family: fontRegular
      fonts:
        - asset: assets/fonts/NunitoSansRegular.ttf
    - family: fontMedium
      fonts:
        - asset: assets/fonts/NunitoSansBlack.ttf
    - family: fontBold
      fonts:
        - asset: assets/fonts/NunitoSansBold.ttf
    - family: fontExtraBold
      fonts:
        - asset: assets/fonts/NunitoSansExtraBold.ttf
    - family: fontSemiBold
      fonts:
        - asset: assets/fonts/NunitoSansSemiBold.ttf
