class ApiUrl {
//  static const liveApiUrl = "https://queryfinders.com/meditrack/public/api/";
  static const buildApiUrl = "http://192.168.1.9/qfs_ecommerce/api/";
  static const register = 'registration';
  static const login = 'login';
  static const banner = 'banner/list';
  static const updatePassword = 'update_forgot_password';
  static const getForgotPasswordOtp = 'forgot_password_otp';
  static const getVerifyOtp = 'verify_forgot_otp';
  static const getVerifyGuestOtp = 'verify_guest_login_otp';
  static const getSignUpOtp = 'get_guest_login_otp';
  static const updateForgotPassword = 'update_forgot_password';
  static const changePassword = 'change_password';
  static const getCategory = 'product/category/list';
  static const getSubCategory = 'product/sub/category/list';
  static const getInnerSubCategory = 'product/inner/sub/category/list';
  static const addAddress = 'address/add';
  static const updateAddress = 'address/update/';
  static const getAddress = 'address/list';
  static const getOrderList = 'order/list';
  static const getBlogTypeList = 'blog/type/list';
  static const getBlogList = 'blog/list?page=';
  static const getProductList = 'product/list';
  static const getBrandList = 'brand/list';
  static const getHome = 'product/trend/list';
  static const getSearch = 'product/search';
  static const review = 'review';
  static const getState = 'get_state';
  static const getCity = 'get_city';
  static const getUser = 'user/get';
  static const updateUser = 'user/update';
  static const addFavourite = 'favorite';
  static const getFavourite = 'favorite_list';
  static const addDefaultAddress = 'address/setDefaultAddress';
}
